### ISSUE TITLE
Replay a Video?

### ISSUE THREAD

**Issue by kenjimelody** [BrightcoveOS/android-player-samples#100]
i have a question about Brightcove SDK for Android

Can i replay a video when i clicked a rewind button?
i don't want a rewind button. can i custom the brightcove player?

let me know about this solution.
Thanks!

**Comment by jskcse4** [comment]
I too need a help on this issue...

**Comment by thase** [comment]
Hi,

You can check out the PlayerUICustomization sample app to see how create all kinds of different layouts with custom views/button with the PlayerUI:

https://github.com/BrightcoveOS/ios-player-samples/tree/master/PlayerUI/PlayerUICustomization/objc

Specifically, here is where we add a UIButton to the control layout and assign it a custom action:

https://github.com/BrightcoveOS/ios-player-samples/blob/master/PlayerUI/PlayerUICustomization/objc/PlayerUICustomization/ViewController.m#L380-L389

Note "Tap Me" button does custom action (show "Tapped!" in the screen). You could implement your own handler for the button (e.g. seek back to the begin to implement replay)

**Comment by BCjwhisenant** [comment]
Closing, answered.
