### ISSUE TITLE
Sample Account, Policy and Video Id's wrong - onError callback not firing.

### ISSUE THREAD

**Issue by dominicthomas** [BrightcoveOS/android-player-samples#112]
These values in the sample applications are not working. Pulling the values from the iOS sample applications worked though.. The demo values need updating in this project but it does indicate issues with error handling.

The onError callback was not being fired when calling catalog.findVideoByID with bad values. There is also not good enough error reporting in the android logs to indicate these errors. The onError callback should be firing with detailed information on a invalid policy, catalog, or videoId and this was not happening.

I noticed in the android log that it said video not found.. changed the value and still no callback.. then clicked the url that the player was trying to access "https://edge.api.brightcove.com/playback/v1/accounts/3636334163001/videos/3987127390001" and only in there saw that there was a INVALID_POLICY_KEY  error.

**Comment by dominicthomas** [comment]
Code being called:

`        // Add the video found in the catalog
        final EventEmitter eventEmitter = brightcoveVideoView.getEventEmitter();
        final Catalog catalog = new Catalog(eventEmitter, getString(R.string.account), getString(R.string.policy));
        catalog.findVideoByID(getString(R.string.videoId), new VideoListener() {
            @Override
            public void onVideo(final Video video) {
                video.getProperties();
                Log.v(TAG, "onVideo: video = " + video);
                brightcoveVideoView.add(video);
                brightcoveVideoView.start();
            }

            @Override
            public void onError(String error) {
                super.onError(error);
                throw new RuntimeException(error);
            }
        });`

**Comment by dominicthomas** [comment]
`        // Add the video found in the catalog
        final EventEmitter eventEmitter = brightcoveVideoView.getEventEmitter();
        final Catalog catalog = new Catalog(eventEmitter, getString(R.string.account), getString(R.string.policy));
        catalog.findVideoByID(getString(R.string.videoId), new VideoListener() {
            @Override
            public void onVideo(final Video video) {
                video.getProperties();
                Log.v(TAG, "onVideo: video = " + video);
                brightcoveVideoView.add(video);
                brightcoveVideoView.start();
            }

            @Override
            public void onError(String error) {
                super.onError(error);
                throw new RuntimeException(error);
            }
        });`

**Comment by dominicthomas** [comment]
'final EventEmitter eventEmitter = brightcoveVideoView.getEventEmitter();
        final Catalog catalog = new Catalog(eventEmitter, getString(R.string.account), getString(R.string.policy));
        catalog.findVideoByID(getString(R.string.videoId), new VideoListener() {
            @Override
            public void onVideo(final Video video) {
                video.getProperties();
                Log.v(TAG, "onVideo: video = " + video);
                brightcoveVideoView.add(video);
                brightcoveVideoView.start();
            }

            @Override
            public void onError(String error) {
                super.onError(error);
                throw new RuntimeException(error);
            }
        });'

**Comment by dominicthomas** [comment]
Code being called:

        // Add the video found in the catalog
        final EventEmitter eventEmitter = brightcoveVideoView.getEventEmitter();
        final Catalog catalog = new Catalog(eventEmitter, getString(R.string.account), getString(R.string.policy));
        catalog.findVideoByID(getString(R.string.videoId), new VideoListener() {
            @Override
            public void onVideo(final Video video) {
                video.getProperties();
                Log.v(TAG, "onVideo: video = " + video);
                brightcoveVideoView.add(video);
                brightcoveVideoView.start();
            }

            @Override
            public void onError(String error) {
                super.onError(error);
                throw new RuntimeException(error);
            }
        });

**Comment by dominicthomas** [comment]
Working details:
<string name="account">3636334180001</string>
<string name="policy">BCpkADawqM1Sh_RsWQTEtCCpMbpKrbKQN_lhGY3fSZE-Cbp67h2aDRTDuifFXnT3yEYrxPNy640VTr224uWjtky-6YDzzqIDRyjqZq_wXu4Py0MSUMdf2rPmS102D6QGi8bIEQEXutS-eeVp</string>
<string name="videoId">3987127390001</string>

**Comment by BCjwhisenant** [comment]
Hello @dominicthomas 
Can you indicate which samples are not working as expected? I searched the repo for "3636334163001,"  the account ID from the original post, and found it in only two samples. I checked those samples, and both load and play their videos as expected. I then checked several of the other samples, and they are working as expected for me as well.

I modified the policy keys for the two samples that use account 3636334163001, to trigger an error, and did note that the MainActivity does log an error message, although it does not mention an invalid policy key:
```
07-06 18:02:09.906 8465-8465/? D/MainActivity: error { message: Error accessing URI: https://edge.api.brightcove.com/playback/v1/accounts/3636334163001/videos/3637773814001: https://edge.api.brightcove.com/playback/v1/accounts/3636334163001/videos/3637773814001 }
```
That said, we do have plans (although no expected release date as yet) to enhance the error handling and reporting in the SDKs.

**Comment by BCjwhisenant** [comment]
I'm going to close this, based on inactivity.
Please re-open with details if the issue persists.
