### ISSUE TITLE
VMAP not working

### ISSUE THREAD

**Issue by mypplication** [BrightcoveOS/android-player-samples#114]
Your VMAPSample in exoplayer folder  is not functional. 
If you run the application several times, and there is no advertising, the video does not start automatically, and it will be impossible to start it manually.

https://github.com/BrightcoveOS/android-player-samples/tree/master/brightcove-exoplayer/VMAPSampleApp

Test on Samsung GS5 with Android 6.0.1 and Nexus 9 with Android N
SDK 4.8.3 brightcove

**Comment by BCjwhisenant** [comment]
Closing this, outdated issue.
