### ISSUE TITLE
Gradle sync fails with samples

### ISSUE THREAD

**Issue by tomblenz** [BrightcoveOS/android-player-samples#123]
I have cloned and imported via VCS into Android Studio, however the gradle sync fails with this message.

> Error:Unable to load class 'org.gradle.logging.ProgressLogger'.
> Possible causes for this unexpected error include:<ul><li>Gradle's dependency cache may be corrupt (this sometimes occurs after a network connection timeout.)
> <a href="syncProject">Re-download dependencies and sync project (requires network)</a></li><li>The state of a Gradle build process (daemon) may be corrupt. Stopping all Gradle daemons may solve this problem.
> <a href="stopGradleDaemons">Stop Gradle build processes (requires restart)</a></li><li>Your project may be using a third-party plugin which is not compatible with the other plugins in the project or the version of Gradle requested by the project.</li></ul>In the case of corrupt Gradle processes, you can also try closing the IDE and then killing all Java processes.

I have attempted both options listed above, including a full system restart.  Other projects sync ok.

**Comment by duckinferno** [comment]
After tootling around I managed to fix it by updating `de.undercouch:gradle-download-task` to version 3.1.2 and 

`apply plugin: 'download-task'`

to

`apply plugin: 'de.undercouch.download'`

in the base project build.gradle

**Comment by saravananmaruthanayakam** [comment]
@duckinferno  After I have done the above,I'm getting this error,
Error:Could not find de.undercouch:gradle-download-task:3.1.2 .
Searched in the following locations:
    file:/C:/Program Files/Android/Android Studio/gradle/m2repository/de/undercouch/gradle-download-task/3.1.2 /gradle-download-task-3.1.2 .pom
    file:/C:/Program Files/Android/Android Studio/gradle/m2repository/de/undercouch/gradle-download-task/3.1.2 /gradle-download-task-3.1.2 .jar
    https://jcenter.bintray.com/de/undercouch/gradle-download-task/3.1.2 /gradle-download-task-3.1.2 .pom
    https://jcenter.bintray.com/de/undercouch/gradle-download-task/3.1.2 /gradle-download-task-3.1.2 .jar
Required by:
    :android-player-samples-master:unspecified

**Comment by saravananmaruthanayakam** [comment]
@duckinferno After I've done the above,I'am getting this error .I don't know why the 



> gradle-download-task-3.1.2

Error:Could not find de.undercouch:gradle-download-task:3.1.2 .
Searched in the following locations:
    file:/C:/Program Files/Android/Android Studio/gradle/m2repository/de/undercouch/gradle-download-task/3.1.2 /gradle-download-task-3.1.2 .pom
    file:/C:/Program Files/Android/Android Studio/gradle/m2repository/de/undercouch/gradle-download-task/3.1.2 /gradle-download-task-3.1.2 .jar
    https://jcenter.bintray.com/de/undercouch/gradle-download-task/3.1.2 /gradle-download-task-3.1.2 .pom
    https://jcenter.bintray.com/de/undercouch/gradle-download-task/3.1.2 /gradle-download-task-3.1.2 .jar
Required by:
    :android-player-samples-master:unspecified

**Comment by duckinferno** [comment]
@saravananmaruthanayakam No idea sorry.  I only changed those two lines.

**Comment by sergiomartinez4** [comment]
are you guys using the gradle wrapper? or what version of gradle are you using?

**Comment by rabross** [comment]
@duckinferno This could be worth a PR.
@sergiomartinez4 Using the wrapper, yes. Version 2.14.1. It also works without the wrapper on version 3.3.

**Comment by whenyoubelieve2014** [comment]
+1

This build error is happening to me as well. Reported on SO: https://stackoverflow.com/questions/43809186/unable-to-load-class-org-gradle-logging-progresslogger

**Comment by sergiomartinez4** [comment]
Let's step back a little.
I would like to be able to reproduce the initial issue, and I'm assuming there's a compatibility issue with any tool or library, and I'd like to know which one is causing it.

I just checked out the source having the latest changes, which is pointing to the anpVersion=4.13.+
I open AndroidStudio and imported the project without problems. I'm currently using Android Studio 2.2.2, and Android Studio is using the gradle wrapper included in the project (2.14.1). I'm also using Java 8.

I also built the project from the command line and was successful:
$ ./gradlew build

I can see that by updating de.undercouch:gradle-download-task fixed the problem for some, but I wonder what caused that compatibility issue i the first place.

Please verify you're using the same tools version as above and share if you still have the problem.
You could also run the Android Manager and update the Android SDK tools and build tools and any other SDK platform needed.

Another thing you could try is to isolate the Module that has the problem, by commenting out every project in settings.gradle file and just leaving one or a few of them. That will help to rule out any third party library as IMA or Freewheel.

Please share any results.
Thanks

**Comment by sergiomartinez4** [comment]
Please reopen if you still face the same problem
