### ISSUE TITLE
Distorted Video on API 19

### ISSUE THREAD

**Issue by marcJV** [BrightcoveOS/android-player-samples#126]
This is currently only happening on a Samsung Galaxy S4 on API 19.

The first chunk of video loaded is always distorted, and then later it "fixes" itself to show a valid video.

The same thing occurs when the app is navigated away from, and back to.

The only error that I see in the console that would relate to this is as follows:

```
E/ACodec: [OMX.qcom.video.decoder.avc] storeMetaDataInBuffers failed w/ err -2147483648
```

**Comment by BCjwhisenant** [comment]
Closing, outdated.
