### ISSUE TITLE
How to stream mp3, m4v, wav media files on Brightcove palyer?

### ISSUE THREAD

**Issue by khaleeljageer** [BrightcoveOS/android-player-samples#128]
I found a documentation which play audio files using [brightcove player](https://docs.brightcove.com/en/video-cloud/media-management/guides/audio-content.html). How to achieve this with android Brightcove player SDK?

I'm using player version = 4.13.x

**Comment by sergiomartinez4** [comment]
Hi @khaleeljageer 
Thanks for reaching out.
So after you ingest audio through Video Cloud, following the steps provided in the website above, you can play them using the Brightcove player SDK without any problem, as you would normally do with any other video from your catalog.

Please note that the files has to be transcoded to use MP4 or HLS as stated in the website.
If you have further questions, let me know.
Regards!

**Comment by khaleeljageer** [comment]
Hi @sergiomartinez4 thanks... I got the point.
