### ISSUE TITLE
Stretch Video in <com.brightcove.player.view.BrightcoveExoPlayerVideoView /> to fit screen programmatically

### ISSUE THREAD

**Issue by cristarra** [BrightcoveOS/android-player-samples#147]
I tried various ways to change the view via xml as below:

`<com.brightcove.player.view.BrightcoveExoPlayerVideoView
            android:id="@+id/Player"

            android:layout_width="fill_parent"

            android:layout_height="fill_parent"

            app:resize_mode="fill"

            android:layout_alignParentTop="true"

            android:layout_alignParentBottom="true"

            android:layout_alignParentLeft="true"

            android:layout_alignParentRight="true"

            android:fitsSystemWindows="true"

            android:foregroundGravity="center"

            android:adjustViewBounds="true"

            android:scaleType="fitXY"

            android:layout_gravity="center_horizontal|top"

            tools:layout_editor_absoluteY="0dp"

            android:layout_marginTop="0dp"

            android:layout_marginBottom="0dp"

            android:layout_marginRight="0dp"

            android:layout_marginLeft="0dp"

            android:numColumns="auto_fit"

            android:stretchMode="columnWidth"

            />`

In order for the video inside it can fitXY, but it did not work.

is there any other way by adding to the program code in java?

Like :

`
brightcoveVideoView = (BrightcoveExoPlayerVideoView) findViewById(R.id.Player);
brightcoveVideoView.setScaleType(ScaleType.FIT_XY);
`

is there any other simple way to do the above on Brightcove Video View so that the video inside to fit screen programmatically?

**Comment by sergiomartinez4** [comment]
You could try to scale it programatically. Please check this forum post: https://groups.google.com/d/msg/brightcove-native-player-sdks/4mcA6fhf1fU/dViC5MTQAwAJ
That should help you get started.
Hope that helps

**Comment by cristarra** [comment]
@sergiomartinez4 This is very helpful, my problem has been solved.

Thank you very much.
