### ISSUE TITLE
Implement ActivityLifecycleCallbacks

### ISSUE THREAD

**Issue by ncuillery** [BrightcoveOS/android-player-samples#148]
How do you guys feel about making the [LifecycleUtil](https://brightcovelearning.github.io/Brightcove-API-References/android-sdk/javadoc/com/brightcove/player/util/LifecycleUtil.html) class implementing [ActivityLifecycleCallbacks](https://developer.android.com/reference/android/app/Application.ActivityLifecycleCallbacks.html)?

The class already have all the methods of the interface with the correct names.

So that, we could directly do:

```java
getApplication().registerActivityLifecycleCallbacks(new LifecycleUtil(playerView));
```

for those who can't or don't want to inherit from `BrightcovePlayer`.

EDIT: I didn't try it but I guess we could implement [FragmentLifecycleCallbacks](https://developer.android.com/reference/android/support/v4/app/FragmentManager.FragmentLifecycleCallbacks.html) as well.

**Comment by sergiomartinez4** [comment]
@ncuillery Thanks for the suggestion, we'll definitely take a look 👍

**Comment by BCjwhisenant** [comment]
Closing, this is outdated. Please open a [support ticket](https://sdks.support.brightcove.com/support/opening-case-with-brightcove-support.html) if you are experiencing issues.
