### ISSUE TITLE
Video Quality Selection

### ISSUE THREAD

**Issue by quangnn041291** [BrightcoveOS/android-player-samples#152]
How to enable Video Quality Selection? Thanks!

**Comment by sergiomartinez4** [comment]
Hi @quangnn041291 ,

Could you please explain more what you want to do? what version of the SDK you are using? and what player?
If you want to select a maximum bitrate, you can use [ExoPlayerVideoDisplayComponent.setPeakBitrate](https://brightcovelearning.github.io/Brightcove-API-References/android-sdk/javadoc/com/brightcove/player/display/ExoPlayerVideoDisplayComponent.html#setPeakBitrate-int-).

If you are interested in selecting the bitrate manually, you can check [this thread](https://groups.google.com/forum/#!searchin/brightcove-native-player-sdks/exoplayer$20tracks%7Csort:date/brightcove-native-player-sdks/w3FDeMN-I7Q/zAR5Me8rAwAJ) for info when using ExoPlayer v1 (deprecated in the latest version of the SDK).

Besides, I recommend posting directly to the [Brightcove Native Player SDK forum](https://groups.google.com/forum/#!forum/brightcove-native-player-sdks) to get more visibility and help.

Thanks!
Sergio

**Comment by quangnn041291** [comment]
Thank you @sergiomartinez4 
I want to change the video resolution manually, such as: 480p, 720p, 1080p,... or Auto

**Comment by sergiomartinez4** [comment]
@quangnn041291 in that case, I believe [the thread](https://groups.google.com/forum/#!searchin/brightcove-native-player-sdks/exoplayer$20tracks%7Csort:date/brightcove-native-player-sdks/w3FDeMN-I7Q/zAR5Me8rAwAJ)  mentioned earlier will be useful to do that.
You can get the track Format with `player.getTrackFormat(trackType, i);` and that object has information like the video resolution. Be aware that the video manifest might have duplicate video resolutions with different bitrates, so you must handle the specific track selection.

It's on our roadmap to provide a easier way to handle the quality selection, but there's not a date for this yet.

**Comment by congtuyenvip** [comment]
@sergiomartinez4  Why can't baseVideoView.getSourceController().selectSource() change video quality and take no effect? I see it's does not seem to emit event selection source , right?

**Comment by sergiomartinez4** [comment]
@congtuyenvip `baseVideoView.getSourceController().selectSource()` is in the context of the Catalog response, where you might get different kind of sources type, such as MP4, DASH or HLS. Thus `baseVideoView.getSourceController().selectSource(video)` will search inside the video object sources and select as the first option a DASH source, if not it will look for an HLS source or else it will search for an MP4 source.
This method is usually used internally to select the right source to play and it's independent of the quality selection.

**Comment by RageshAntony** [comment]
> It's on our roadmap to provide a easier way to handle the quality selection, but there's not a date for this yet.

What about the current status ? @sergiomartinez4

**Comment by jrw95** [comment]
@RageshAntony This feature has not moved up the roadmap, sorry.
