### ISSUE TITLE
Getting Invalid Token ErrorCode: 210

### ISSUE THREAD

**Issue by himanshugeraalgoworks** [BrightcoveOS/android-player-samples#154]
Hey I am new to this, getting  Error JSON: '{"error": "invalid token","code":210}' response when using readAPI.findVideoById(Long.parseLong(videoId),
							videoFields, null);

**Comment by BCjwhisenant** [comment]
Hello,
- Which app are you running when you see this error?

Each of the sample apps provides an example of how to configure the Catalog object, and how to retrieve a video from your account.
If you want to use the findVideoByID method, simply replace the findVideoByReferenceID call in a sample app with findVideoByID, and use the video ID that you want to load into the player. The other argument, a VideoListener object, is the same for either findVideoByReferenceID or findVideoByID.

If you're still stuck, please let us know which app you're using, and if possible, a code sample.

**Comment by BCjwhisenant** [comment]
Closing this, no response received.
