### ISSUE TITLE
Full Screen support for video views in recycler views

### ISSUE THREAD

**Issue by cray85** [BrightcoveOS/android-player-samples#171]
Possibly related to #148 - this is a very common use case so it would be nice to see this added. In the long run you may want to refactor your code to favour composition over inheritance so that your customers don't have to deal with issues such as this (inheriting from base Brightcove activity and fragment classes isn't always feasible).

EDIT: The fullscreen button is visible onscreen, but doing it merely hides the phone status bar.

**Comment by sergiomartinez4** [comment]
hi @cray85 
Sorry for the late reply. 
Thanks for your interest in our SDK and for the suggestions. If this feature is really important to your users and want it to be part of the Brightcove SDK, I highly suggest to open a support request in https://help.brightcove.com/en/contact
This will help to get more attention from our product managers, and it will be properly prioritized.

If you have any other question or comment, feel free to post it in our public forum: https://groups.google.com/forum/#!forum/brightcove-native-player-sdks

Thanks
