### ISSUE TITLE
BrightcovePlayer

### ISSUE THREAD

**Issue by AmanSharma1997** [BrightcoveOS/android-player-samples#187]
This class is missing please check this and resolve this issue ASAP sir.

Thank You

**Comment by BCjwhisenant** [comment]
Can you provide more detail, please?
A build log and steps to reproduce the problem would be most helpful.
Thanks!

**Comment by BCjwhisenant** [comment]
Closing, this is outdated. Please open a [support ticket](https://sdks.support.brightcove.com/support/opening-case-with-brightcove-support.html) if you are still having issues.
