### ISSUE TITLE
Brightcove seekbar on Android TV

### ISSUE THREAD

**Issue by hantrungkien** [BrightcoveOS/android-player-samples#190]
Thanks for Brightcove Team.
I have use Brightcove Android SDK for my project on Android TV but when BrightcoveSeekBar was focused and dragged by DPAD then variable "dragging" in BrightcoveSeekBarController always is true. I hard tried set it to false but I can't.
Please help me. Many thanks!

**Comment by sergiomartinez4** [comment]
Hi @hantrungkien, sorry for the late reply. I suggest to post in our public forum as we usually have more visibility there: https://groups.google.com/forum/#!forum/brightcove-native-player-sdks

With respect with the dragging variable, I'm not sure I fully understand what you want to achieve. 
The BrightcoveMediaController.isDragging method will be true while dragging the seekbar or when holding either the rewind or fast-forward button. Once the action is complete, it will return false.
I just tried it and I still get that behavior.
If you are getting a different behavior, please let us know what are the steps to reproduce.

**Comment by BCjwhisenant** [comment]
Closing, this is outdated, and was moved to the developer forum. As the developer forum closed in 2020, please open a [support ticket](https://sdks.support.brightcove.com/support/opening-case-with-brightcove-support.html) if there are further issues. Thanks!
