### ISSUE TITLE
Do you have any plan to support MediaController?

### ISSUE THREAD

**Issue by dotkebi** [BrightcoveOS/android-player-samples#192]
Hello.

I'm building an app using brightcove.
However, I am trying to create a player by observing the app's degisn guide
I need a full screen button or something to get a callback.
I can not find it.

Can I help you?

And do you plan to consider interface compatibility with mediaController?

**Comment by sergiomartinez4** [comment]
hi @dotkebi ,
Have you checked [CustomizedControlsSampleApp](https://github.com/BrightcoveOS/android-player-samples/tree/master/brightcove-player-controls/CustomizedControlsSampleApp) or [StyledControlsSampleApp](https://github.com/BrightcoveOS/android-player-samples/tree/master/brightcove-player-controls/StyledControlsSampleApp)? Each of these sample app have a readme with helpful information related to the controls.

The CustomizedControlsSampleApp shows you how to add a new button and add a callback. The StyledControlsSampleApp shows you how to hide existing buttons.

With respect to support for Android MediaController, I highly suggest to open a support request in https://help.brightcove.com/en/contact/create
This will help to get more attention from our product managers, and it will be properly prioritized.

**Comment by BCjwhisenant** [comment]
Closing this as answered.
