### ISSUE TITLE
play-services-ads is out of date

### ISSUE THREAD

**Issue by awscherb** [BrightcoveOS/android-player-samples#218]
Dependency `com.google.android.gms:play-services-ads` as used in `brightcove-exoplayer/AdRulesIMASampleApp` uses version `11.0.4` and is several years out of date. Bumping to latest version `19.0.4` causes compilation to fail.

**Comment by sergiomartinez4** [comment]
Hi @awscherb ,
Thanks for bringing this to our attention. We are planning to update the `play-services-ads` version along with the `IMA SDK` version soon.
However, we should be using the `play-services-ads` version **18.3.0**. This is the version used in the Brightcove SDK, so you should not have a problem using it. I will update it in the sample apps too

**Comment by BCjwhisenant** [comment]
Closing, this is on the team backlog.
