### ISSUE TITLE
Not able to resume a video to download after a day

### ISSUE THREAD

**Issue by SurajBahadur** [BrightcoveOS/android-player-samples#232]
Hello BrightCove Team, 
Below is what I'm trying to do:

Step 1: To download any video, I've first request a license to download a video, and on success calling the downloadVideo() by passing video information. 

Step 2: Pause a downloading video then resume it on the same day, It starts downloading the video from the last position.

Step 3: But when I resume a video the next day then it is not resuming a video and simply it gives a 0 as a status. Below is the code snippet of the resume method.

Note: Can you please let me know why this behavior comes when trying to resume video the next day. Also do let me know what are other factors may responsible for resuming the video.

```
public void resumeVideoDownload(@NonNull
                                Video video,
                                @NonNull
                                OfflineCallback<java.lang.Integer> callback)
This method is used to asynchronously resume the download of a video which was previously paused.
Parameters:
video - the video to resume its download.
callback - Provides the result of the operation. In case the download of the requested video has been resumed successfully, OfflineCallback.onSuccess(Object) will be called to provide an Integer value of its current DownloadStatus.StatusCode. OfflineCallback.onFailure(Throwable) will be called in case there was an error. UnsupportedOperationException if the underlying download process does not support pausing video downloads.
```

**Comment by nandovelazquez** [comment]
Hello @SurajBahadur,

Could you share a log file with the info threw by the device, please?

**Comment by BCjwhisenant** [comment]
Closing. No response from the original poster. Please reopen this if there are further issues.
