### ISSUE TITLE
Download Notification

### ISSUE THREAD

**Issue by HasanElHefnawy** [BrightcoveOS/android-player-samples#233]
As per [docs](https://sdks.support.brightcove.com/android/resources/code-snippets-using-native-sdk-android.html#Offline_playback_with_DRM):
For videos downloaded for offline playback, the download status **can** also be shown in the Notification Area. The notification title is set to the video title. The notification is removed if the download is paused or cancelled.

Is it possible to hide the notification even if the download is in progress?
If not possible, how to change the notification title and how to make a specific action when the notification is clicked?

**Comment by nandovelazquez** [comment]
Hello @HasanElHefnawy. 
The video download process runs in a second thread and Android requires displaying a notification for all the background processes, therefore, the notification cannot be avoided nor be hidden.

Also, setting a custom title is not currently supported by the Brightcove SDK. But you can create a request ticket following this process 
https://sdks.support.brightcove.com/support/opening-case-with-brightcove-support.html

**Comment by BCjwhisenant** [comment]
Closing as Answered.
