### ISSUE TITLE
Error: unable to find valid certification path to requested target

### ISSUE THREAD

**Issue by Nicu1991** [BrightcoveOS/android-player-samples#235]
I am using some brightcove dependencies in my code: 

repositories {
    google()
    maven {
        url 'http://repo.brightcove.com/releases'
    }
    mavenCentral()
    jcenter()
}

dependencies {
     implementation "com.brightcove.player:android-sdk:6.16.4"
     implementation "com.brightcove.player:exoplayer2:6.16.4"
}

Recently I started to migrate all libraries from jcenter to maven (this is required by Google), so now I have this in repositories section:

repositories {
    google()
    maven {
        url 'https://repo.brightcove.com/releases'
    }
    mavenCentral()
}

As you can see, I also changed the brightcove url from http to https based on the documentation (https://sdks.support.brightcove.com/android/basics/step-step-simple-video-app-using-native-sdk-android.html#Create_a_project), but now I am getting an error:

 > Could not resolve com.brightcove.player:exoplayer2:6.16.4.
         > Could not get resource 'https://repo.brightcove.com/releases/com/brightcove/player/exoplayer2/6.16.4/exoplayer2-6.16.4.pom'.
            > Could not HEAD 'https://repo.brightcove.com/releases/com/brightcove/player/exoplayer2/6.16.4/exoplayer2-6.16.4.pom'.
               > PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

I've tried using the http instead on https as I used in the past, but I am still receiving another error:

Could not find com.google.android.exoplayer:exoplayer-core:2.10.8.
Required by:
    project :sample > com.brightcove.player:exoplayer2:6.16.4

Is the library working only in combination with jcenter() and url 'http://repo.brightcove.com/releases' or is there something else that I need to do in order to make it working without jcenter()?

**Comment by Nicu1991** [comment]
After some more investigations, I've found that issue is that the the Android Brightcove Native SDK version 6.16.4 is using an old version of com.google.android.exoplayer:exoplayer, 2.10.8 (please see the errors below) that was published only on jcenter repository. Based on the ExpoPlayer documentation (https://github.com/google/ExoPlayer/blob/release-v2/RELEASENOTES.md), only with version 2.13.3 (2021-04-14) the ExpoPlayer was published to the Google Maven repository. So can you please update the Android Brightcove Native SDK to use the latest version of ExpoPlayer that is in Google Maven repository? Thank you

Failed to resolve: com.google.android.exoplayer:exoplayer-hls:2.10.8
Failed to resolve: com.google.android.exoplayer:exoplayer-ui:2.10.8
Failed to resolve: com.google.android.exoplayer:exoplayer-core:2.10.8
Failed to resolve: com.google.android.exoplayer:exoplayer-dash:2.10.8

**Comment by BCjwhisenant** [comment]
@Nicu1991 Thank you for checking this out. We will be looking into this.

**Comment by BCjwhisenant** [comment]
This is answered, and noted to the team to be aware of during our ExoPlayer upgrade.
