### ISSUE TITLE
Usage of Jcenter

### ISSUE THREAD

**Issue by diofelpallega** [BrightcoveOS/android-player-samples#241]
hi guys, I tried using brightcove but removing jcenter() on my gradle since it's deprecated and it seems brightcove is requiring jcenter() to be  imported as I'm having error if I do so. Am I correct that brightcove needs jcenter?

**Comment by BCjwhisenant** [comment]
Hello @diofelpallega ,
Apologies for such a late reply, but I tried removing `jcenter()` from the build.gradle of this repo, and then running a Gradle sync (in Android Studio) with a few different versions of the Brightcove Android SDK: 6.16.5, 6.17.1, and 6.18.0. I tried this approach to ensure that the libraries for the specified version were downloaded, which they were. Further, I did a search for `jcenter` through the internal build.gradle files in the SDK itself. No results were returned.

If you're still experiencing problems, please [open a case through our support portal](https://sdks.support.brightcove.com/support/opening-case-with-brightcove-support.html), and include:
- The SDK version(s) where you're seeing the issue
- The dependencies that are failing to download

Thank you.
