### ISSUE TITLE
BrightCove Player Controls doesn't work in Full Screen Mode

### ISSUE THREAD

**Issue by singh88harman** [BrightcoveOS/android-player-samples#253]
on OnePlus 7T, Android version 11. We tested AppCompatFragmentSampleApp from this repo and it's not working. 
On same device, when we run video in full screen mode, video controls play/pause button, seek bar click doesn't work. 
Device info attached.
![screenshot_20220413-140231](https://user-images.githubusercontent.com/1227976/163140544-8660692d-7004-493d-8edb-ff38e7a4fb6a.jpeg)

**Comment by nandovelazquez** [comment]
We are closing the Issues feature for this repo next month. If your problem persists, please report it as an issue through our support page: https://sdks.support.brightcove.com/developer-support/questions/report-issue-brightcove-native-sdks.html

**Comment by nandovelazquez** [comment]
We are closing the Issues feature for this repo next month. If your problem persists, please report it as an issue through our support page: https://sdks.support.brightcove.com/developer-support/questions/report-issue-brightcove-native-sdks.html
