### ISSUE TITLE
Hide close button and remove white space

### ISSUE THREAD

**Issue by Ahmeddji** [BrightcoveOS/android-player-samples#254]
Hi,

In Brightcove Exoplayer VideoView, in some devices there comes a close button. How can I hide that close button? I tried to search in the docs but I didn't find anything about it.

Also in every video, there comes white space at both sides of the the screen left and right, how can I remove that white space?

https://drive.google.com/file/d/1lh8YsuF_fvBNkF_BcC4WpqvIW_nmHrMa/view?usp=sharing

Thanks.

**Comment by jrw95** [comment]
@Ahmeddji Can you tell us what some of the devices are that you're seeing the close button problem with?
Also, the SDK version?

As for the white bars issue (a different issue from the close button issue), we'll look into that one too.
Thanks for raising these.

**Comment by Ahmeddji** [comment]
@jrw95 I am seeing the close button in Samsung S10. SDK version is 6.18.1.

**Comment by nandovelazquez** [comment]
We are closing the Issues feature for this repo next month. If your problem persists, please report it as an issue through our support page: https://sdks.support.brightcove.com/developer-support/questions/report-issue-brightcove-native-sdks.html
