### ISSUE TITLE
Stop audio recording of video in brightcove player

### ISSUE THREAD

**Issue by SurajBahadur** [BrightcoveOS/android-player-samples#257]
Is there any way to stop the audio recording of the video of the app in the Brightcove player.  It tried this but it doesn't work. 

```
val mExoPlayer = (binding.mybrightCoveView.videoDisplay as ExoPlayerVideoDisplayComponent).exoPlayer
        if (mExoPlayer is SimpleExoPlayer) {
            // Get SimpleExoPlayer
            val simpleExoPlayer = mExoPlayer as SimpleExoPlayer
            AudioAttributes.Builder()
                .setAllowedCapturePolicy(ALLOW_CAPTURE_BY_NONE)
                .build().also {
                    simpleExoPlayer.audioComponent?.setAudioAttributes(it, false)
                }
        }
```

**Comment by SurajBahadur** [comment]
Any update on this

**Comment by jrw95** [comment]
Hello @SurajBahadur How is the audio being recorded? Through a separate app, code in the player activity itself, something else?

**Comment by SurajBahadur** [comment]
@jrw95 audio is getting recorded by a third-party app i.e screen recorder. For Example, I'm playing a paid video using Brightcove player and someone is using the screen recorder app Secondly, I've also used the FLAG_SECURE which makes the screen black while any recording happens. But the user is able to record the audio of the video. So please provide me a solution to protect the audio from getting recorded OR any patch to handle this scenario.

**Comment by SurajBahadur** [comment]
@jrw95 any update on this?

**Comment by jrw95** [comment]
Currently the Brightcove Android SDK does not itself provide copy protection. Based on a search for "android disable audio recording," this may not be feasible.
