### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'void com.brightcove.player.util.LifecycleUtil.onActivityCreated(android.os.Bundle)' on a null object reference

### ISSUE THREAD

**Issue by droider91** [BrightcoveOS/android-player-samples#258]
Getting `NPE` while playing the video player in fragment.

` Process: com.example.myapplication, PID: 9006
    java.lang.NullPointerException: Attempt to invoke virtual method 'void com.brightcove.player.util.LifecycleUtil.onActivityCreated(android.os.Bundle)' on a null object reference
        at com.example.myapplication.ui.home.BCPlayer.onActivityCreated(BCPlayer.java:71)
        at androidx.fragment.app.Fragment.performActivityCreated(Fragment.java:3028)
        at androidx.fragment.app.FragmentStateManager.activityCreated(FragmentStateManager.java:578)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:264)
        at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:113)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1374)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2841)
        at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2784)
        at androidx.fragment.app.Fragment.performActivityCreated(Fragment.java:3034)
        at androidx.fragment.app.FragmentStateManager.activityCreated(FragmentStateManager.java:578)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:264)
        at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:113)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1374)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2841)
        at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2784)
        at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:262)
        at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:478)
        at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:246)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1455)
        at android.app.Activity.performStart(Activity.java:8076)
        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3660)
        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2210)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7839)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)`

BCPlayer.java

```
@ListensFor(
        events = {"fragmentSaveInstanceState"}
)
public class BCPlayer extends Fragment {

    public static final String TAG = BCPlayer.class.getSimpleName();
    protected BaseVideoView brightcoveVideoView;
    private LifecycleUtil lifecycleUtil;
    private EventLogger eventLogger;

    public BrightcoveVideoView getBrightcoveVideoView() {
        BrightcoveVideoView result = null;
        if (this.brightcoveVideoView instanceof BrightcoveVideoView) {
            result = (BrightcoveVideoView)this.brightcoveVideoView;
        }

        return result;
    }

    public BaseVideoView getBaseVideoView() {
        return this.brightcoveVideoView;
    }

    public void fullScreen() {
        if (!this.brightcoveVideoView.isFullScreen()) {
            this.brightcoveVideoView.getEventEmitter().emit("enterFullScreen");
        } else {
            Log.e(TAG, "Event emitter is not defined or the video view is already in full screen mode.");
        }

    }

    public void normalScreen() {
        if (this.brightcoveVideoView.isFullScreen()) {
            this.brightcoveVideoView.getEventEmitter().emit("exitFullScreen");
        } else {
            Log.e(TAG, "Event emitter is not defined or the video view is not in full screen mode!");
        }

    }

    public void onActivityCreated(Bundle savedInstanceState) {
        Log.v(TAG, "onActivityCreated");
        super.onActivityCreated(savedInstanceState);
        this.lifecycleUtil.onActivityCreated(savedInstanceState);
    }


    // TODO: Rename parameter arguments, choose names that match
    // the fragment initialization parameters, e.g. ARG_ITEM_NUMBER
    private static final String ARG_PARAM1 = "param1";
    private static final String ARG_PARAM2 = "param2";

    // TODO: Rename and change types of parameters
    private String mParam1;
    private String mParam2;

    public BCPlayer() {
        // Required empty public constructor
    }

    /**
     * Use this factory method to create a new instance of
     * this fragment using the provided parameters.
     *
     * @param param1 Parameter 1.
     * @param param2 Parameter 2.
     * @return A new instance of fragment BCPlayer.
     */
    // TODO: Rename and change types and number of parameters
    public static BCPlayer newInstance(String param1, String param2) {
        BCPlayer fragment = new BCPlayer();
        Bundle args = new Bundle();
        args.putString(ARG_PARAM1, param1);
        args.putString(ARG_PARAM2, param2);
        fragment.setArguments(args);
        return fragment;
    }

    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        if (getArguments() != null) {
            mParam1 = getArguments().getString(ARG_PARAM1);
            mParam2 = getArguments().getString(ARG_PARAM2);
        }
    }
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        Log.v(TAG, "onCreateView");
        View view = super.onCreateView(inflater, container, savedInstanceState);
        if (this.brightcoveVideoView != null) {
            this.lifecycleUtil = new LifecycleUtil(this.brightcoveVideoView);
            this.lifecycleUtil.onCreateView(savedInstanceState, this);
            this.eventLogger = new EventLogger(this.brightcoveVideoView.getEventEmitter(), true, this.getClass().getSimpleName());
            return view;
        } else {
            throw new IllegalStateException("brightcoveVideoView must be assigned before calling onCreateView().");
        }
    }

    public void onStart() {
        Log.v(TAG, "onStart");
        super.onStart();
        this.lifecycleUtil.fragmentOnStart();
    }

    public void onPause() {
        Log.v(TAG, "onPause");
        super.onPause();
        this.lifecycleUtil.fragmentOnPause();
    }

    public void onResume() {
        Log.v(TAG, "onResume");
        super.onResume();
        this.brightcoveVideoView.getEventEmitter().on("changeOrientation", (event) -> {
            int orientation = event.getIntegerProperty("requestedOrientation");
            this.getActivity().setRequestedOrientation(orientation);
        });
        this.lifecycleUtil.fragmentOnResume();
    }

    public void onDestroy() {
        Log.v(TAG, "onDestroy");
        super.onDestroy();
        this.lifecycleUtil.fragmentOnDestroy();
    }

    public void onDestroyView() {
        Log.v(TAG, "onDestroyView");
        super.onDestroyView();
        this.lifecycleUtil.onDestroyView();
    }

    public void onDetach() {
        Log.v(TAG, "onDetach");
        super.onDetach();
        this.lifecycleUtil.onDetach();
    }

    public void onStop() {
        Log.v(TAG, "onStop");
        super.onStop();
        this.lifecycleUtil.fragmentOnStop();
    }

    public void onSaveInstanceState(final Bundle bundle) {
        Log.v(TAG, "onSaveInstanceState");
        this.brightcoveVideoView.getEventEmitter().on("fragmentSaveInstanceState", new EventListener() {
            @Default
            public void processEvent(Event event) {
                BCPlayer.super.onSaveInstanceState(bundle);
            }
        });
        this.lifecycleUtil.fragmentOnSaveInstanceState(bundle);
    }

    @TargetApi(17)
    public void onViewStateRestored(Bundle savedInstanceState) {
        Log.v(TAG, "onViewStateRestored");
        super.onViewStateRestored(savedInstanceState);
        this.lifecycleUtil.onViewStateRestored(savedInstanceState);
    }
}
```

DemoPlayer.java

`
public class DemoFragment extends BCPlayer {

    private static final String ARG_PARAM1 = "param1";

    View v;

    public DemoFragment() {
    }

    /**
     * Use this factory method to create a new instance of
     * this fragment using the provided parameters.
     *
     * @return A new instance of fragment BlankFragment.
     */
    public static DemoFragment newInstance(String color) {
        DemoFragment fragment = new DemoFragment();
        Bundle args = new Bundle();
        args.putString(ARG_PARAM1, color);
        fragment.setArguments(args);
        return fragment;
    }

    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {
        // Inflate the layout for this fragment
        v = inflater.inflate(R.layout.bc_fragment, container, false);
        brightcoveVideoView = v.findViewById(R.id.brightcove_video_view);

        super.onCreate(savedInstanceState);
        String account = "3303963094001";
        String policy = "BCpkADawqM3zXLtsEM0nAyA_3o3TmZnG6bZTXFmjZ8X_rmFMqlpB78l0aiRELs7MWACf4mYN92qMOLMxfZN6Xr3cQ_0R3G2qBiho3X3Nc2yTv7DH4APQ";
        Catalog catalog = new Catalog.Builder(brightcoveVideoView.getEventEmitter(), account)
                .setBaseURL(Catalog.DEFAULT_EDGE_BASE_URL)
                .setPolicy(policy)
                .build();

        catalog.findVideoByID("4283173439001", new VideoListener() {
            @Override
            public void onVideo(Video video) {
                brightcoveVideoView.add(video);
                brightcoveVideoView.start();
            }

            @Override
            public void onError(List<CatalogError> errors) {
                super.onError(errors);
            }
        });

       /* Video video = Video.createVideo("https://media.w3.org/2010/05/sintel/trailer.mp4", DeliveryType.MP4);
        baseVideoView.add(video);
        baseVideoView.getAnalytics().setAccount("1760897681001");
        baseVideoView.start();*/

        return v;
    }
}`

**Comment by jrw95** [comment]
@droider91 If you set a breakpoint at this line in `onActivityCreated` in `BCPlayer`:
```
this.lifecycleUtil.onActivityCreated(savedInstanceState)
```
You will see that that line is reached before the `this.lifecycleUtil` object is initialized (in `onViewCreated`).

I moved this code from `onViewCreated`:
```
        if (this.brightcoveVideoView != null) {
            this.lifecycleUtil = new LifecycleUtil(this.brightcoveVideoView);
            this.lifecycleUtil.onCreateView(savedInstanceState, this);
            this.eventLogger = new EventLogger(this.brightcoveVideoView.getEventEmitter(), true, this.getClass().getSimpleName());
        } else {
            throw new IllegalStateException("brightcoveVideoView must be assigned before calling onCreateView().");
        }
```
to the `onActivityCreated` method, directly before the breakpointed line mentioned above. This fixed the NPE, but then showed that the policy key used in the Catalog call was invalid. I used one of my test accounts and videos, and the content was retrieved and played as expected.

**Comment by droider91** [comment]
Yes. Thank you so much. It's working.
