### ISSUE TITLE
Memory leak on AppCompatActivity

### ISSUE THREAD

**Issue by hrodrick** [BrightcoveOS/android-player-samples#270]
### Description
- Found a memory leak issue which is causing crashes on our app when the user enters and exits a video player repeatedly. 
- I made a fork to create a branch with some changes to reproduce the issue on the AppCompat example app. 

### versions 
- Brightcove : 8.0.0
- Android API : 31

### Reproduction steps 
1. Clone [this repo (my fork)](https://github.com/hrodrick/android-player-samples/tree/issue/Brightcove-notification-memory-leak) please notice that the branch is `issue/Brightcove-notification-memory-leak`
2. Run the AppCompat example app on any emulator, and play the button that says "Play Video"
3. Put the video on full screen
4. Press the back button
5. Once in the initial screen, press the back button again.
6. Open the app again
7. You should see a CanaryLeak notification, tap on it and it will start generating the leaks report.
8. Once finished, tap on it and you can examine the generated leak report, which leaks the PlayerActivity.

of course in the demo app this isn't so consuming, but in our app this leaded to more than 1GB of RAM consumption when entering and exiting the video multiple times, and increases until the app crashes by an ANR.

### Video showing the issue and repro steps
 
![Screen Recording 2023-03-08 at 11 09 40](https://user-images.githubusercontent.com/26490822/223773985-5ac936a0-a052-49ca-bcac-eaa72c87a7c3.gif)
- Sorry it is a gif, the video was too heavy to attach it as is. Please click on it if it doesn't play automatically or already started.

### Changes made on the example app in my fork to reproduce it
- Moved the MainActivity to a PlayerActivity.
- Created a regular MainActivity with a button in the middle, that simply starts the PlayerActivity.
- Added CanaryLeak to the build.gradle file. You can download and learn about it here https://square.github.io/leakcanary/  

### How the issue happens? 
 - It seems that this issue happens because the `ExoMediaPlayback` inside the `VideoDisplay` has a series of listeners which one of them is the `ExoPlayerVideoDisplayComponent.mediaListener`. It is added but never removed, and the leak happens because it access `ExoPlayerVideoDisplayComponent.this.etc`, which in some point of the hierarchy contains reference to the `PlayerActivity` (via the context attribute). 
 - Since this `ExoMediaPlayback.listeners` list is never cleared nor the `mediaListener` never removed, it leaks the whole activity on the memory.

### Workaround
 - By doing some Reflection I could fix this issue on our project. But as reflection implies, it is very "hacky" and may not be compatible with future releases of the library and needs too much effort to work with Obfuscation. 
 Also, it can be easily improved by adding a public clear method (also the cleaning could be done automatically in the BrigthcoveActivity so we don't need to think about it)
```
override fun onDestroy() {
    ...
    try { 
        val playback = baseVideoView.videoDisplay.playback as ExoMediaPlayback
        val listenersField = ExoMediaPlayback::class.java.getDeclaredField("listeners")
        listenersField.isAccessible = true
        listenersField.set(playback, emptySet<ExoMediaPlayback.Listener>())
    } catch (ignored: Throwable) {}
    super.onDestroy()
}
```

### CanaryLeak report file
[BrightcoveCanaryLeakReport.txt](https://github.com/BrightcoveOS/android-player-samples/files/10922939/BrightcoveCanaryLeakReport.txt)

**Comment by nandovelazquez** [comment]
I believe this problem was fixed last year in version 8.2.1.

If your problem persists, please report it as an issue through our support page: https://sdks.support.brightcove.com/developer-support/questions/report-issue-brightcove-native-sdks.html
