### ISSUE TITLE
Video screen is black when setting projection format to EQUIRECTANGULAR (Sample 360 App behaves like this too)

### ISSUE THREAD

**Issue by dillonhafer** [BrightcoveOS/android-player-samples#274]
Sample 360 App behaves the same way

```
dependencies {
  implementation project(':expo-modules-core')
  implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:${getKotlinVersion()}"
  implementation "com.brightcove.player:android-sdk:8.1.0"
  implementation "com.android.support:multidex:2.0.1"
  implementation "com.brightcove.player:exoplayer2:8.1.0"
  implementation "androidx.media:media:1.1.0"
  implementation "com.brightcove.player:android-appcompat-plugin:8.1.0"
}
```

Both examples work perfectly fine on 7.0.0

```kotlin
val projectionFormat =
when (isVR) {
  true -> Video.ProjectionFormat.EQUIRECTANGULAR
  false -> Video.ProjectionFormat.NORMAL
}

var video = Video.createVideo(url, projectionFormat)
player.add(video)
player.start()
```

When projection format is `NORMAL` the video plays fine, when projection format is `EQUIRECTANGULAR` the player controls and timestamps are visible but the video doesn't play.

![NORMAL](https://user-images.githubusercontent.com/1136388/231510540-2a27d1e2-1152-40a2-b767-66440201f185.png)
![EQUIRECTANGULAR](https://user-images.githubusercontent.com/1136388/231510557-c7eb86a5-2774-41f0-b632-bfc667b06ece.png)

**Comment by nandovelazquez** [comment]
We are closing the Issues feature for this repo next month. If your problem persists, please report it as an issue through our support page: https://sdks.support.brightcove.com/developer-support/questions/report-issue-brightcove-native-sdks.html
