### ISSUE TITLE
Custom player style is not applied

### ISSUE THREAD

**Issue by vicpinm** [BrightcoveOS/android-player-samples#275]
I've followed the documentation to customize the seekbar. I've created a new style that inherits from `BrightcoveSeekBarDefault`  like this:

```
   <style name="BrightcoveSeekBar" parent="BrightcoveSeekBarDefault">
        <item name="android:thumb">@drawable/custom</item>
        <item name="android:progressBackgroundTint">#f4511e</item>
        <item name="android:progressTint">#388e3c</item>
        <item name="android:thumbTint">#c51162</item>
    </style>
```
 But the player still looks the same, this style defined in my styles.xml file is not being picked up. Am I missing something else?

**Comment by KquaneAKQA** [comment]
@vicpinm  were you able to resolve this?

**Comment by nandovelazquez** [comment]
We are closing the Issues feature for this repo next month. If your problem persists, please report it as an issue through our support page: https://sdks.support.brightcove.com/developer-support/questions/report-issue-brightcove-native-sdks.html
