### ISSUE TITLE
[Question] READY_TO_PLAY event on background

### ISSUE THREAD

**Issue by Silinde87** [BrightcoveOS/android-player-samples#279]
I've noticed that when I'm playing a video from a list with the screen locked, the [READY_TO_PLAY](https://sdks.support.brightcove.com/android/reference/javadoc/com/brightcove/player/event/EventType.html#READY_TO_PLAY) event is not fired until I unlock the screen, but the [DID_SET_VIDEO](https://sdks.support.brightcove.com/android/reference/javadoc/com/brightcove/player/event/EventType.html#DID_SET_VIDEO) event is always fired, no matter if the screen is locked or unlocked.

So far I was using the first event to control when the video was ready, is it correct the way it works? is there something wrong with it and that's why it behaves like this?

thanks!

**Comment by nandovelazquez** [comment]
We are closing the Issues feature for this repo next month. If your problem persists, please report it as an issue through our support page: https://sdks.support.brightcove.com/developer-support/questions/report-issue-brightcove-native-sdks.html
