### ISSUE TITLE
[CustomVideoPlayerControls] Issue while Customising Player Controls using data binding.

### ISSUE THREAD

**Issue by sumanabhi-rs** [BrightcoveOS/android-player-samples#280]
`current_time` is the key for showcasing the current time of Video.
and this same id is also assign to something in the Leanback.

How to differentiate the id for current_time in this case?

videoplayerui/build/generated/data_binding_base_class_source_out/devDebug/out/com/app/videoplayer/databinding/MediaControllerWithPreviewBinding.java:146: error: package androidx.leanback.R does not exist
      `id = androidx.leanback.R.id.current_time;`
                              ^ 

when the binding is being created it automatically picks the android.leanback.R.id.current_time.

how to overcome this?

**Comment by nandovelazquez** [comment]
We are closing the Issues feature for this repo next month. If your problem persists, please report it as an issue through our support page: https://sdks.support.brightcove.com/developer-support/questions/report-issue-brightcove-native-sdks.html
