### ISSUE TITLE
Applying pending intent in download notification

### ISSUE THREAD

**Issue by SumitProgrammer5955** [BrightcoveOS/android-player-samples#282]
How to apply pending intent in download notification when user wants to see there download progress in specific Activity.

**Comment by nandovelazquez** [comment]
I'm afraid that the SDK does not support that.

We are closing the Issues feature for this repo next month. If you have any other questions, please submit them through our support page: https://sdks.support.brightcove.com/developer-support/questions/report-issue-brightcove-native-sdks.html
