### ISSUE TITLE
Player Control Icons

### ISSUE THREAD

**Issue by osamaahmad95** [BrightcoveOS/android-player-samples#284]
I want to change icons of controls, the change applied on (brightcove_pause_image, brightcove_play_image) successfully, but other not changed(brightcove_closed_captions_image, brightcove_player_options_image, brightcove_rewind_image, brightcove_fast_forward_image).

The controls is buttons, and sample using text(font awesome), but I need to use icon from drawables.

this style:

`    <style name="BrightcoveControlBar" parent="BrightcoveControlBarDefault">
        <item name="brightcove_full_screen">false</item>
        <item name="brightcove_live">false</item>
        <item name="brightcove_timeout">10000</item>
        <item name="brightcove_closed_captions">true</item>
        <item name="brightcove_rewind">true</item>
        <item name="brightcove_fast_forward">true</item>
        <item name="brightcove_closed_captions_image">@drawable/ic_caption</item>
        <item name="brightcove_player_options_image">@drawable/ic_player_settings</item>
        <item name="brightcove_pause_image">@drawable/ic_pause</item>
        <item name="brightcove_fast_forward_image">@drawable/ic_forward</item>
        <item name="brightcove_rewind_image">@drawable/ic_rewind</item>
    </style>`

this is xml layout

`<com.brightcove.player.mediacontroller.BrightcoveControlBar xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:bmc="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:id="@+id/brightcove_control_bar"
    style="@style/BrightcoveControlBar"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="@android:color/transparent"
    android:orientation="horizontal"
    tools:ignore="Overdraw, InconsistentLayout">`

this is button
`<Button
            android:id="@id/fast_forward"
            style="@style/BorderlessButton.TV"
            android:layout_width="26dp"
            android:layout_height="26dp"
            android:visibility="visible"
            android:layout_marginStart="10dp"/>
`

**Comment by nandovelazquez** [comment]
Hi @osamaahmad95. We found an issue customizing those buttons. We also have a PR opened for the fix, and we are planning to release it in v8.2.3.

**Comment by aungtuntunmediacorp** [comment]
Hi, I also having issues in changing custom icons for the player controls. I am using the latest Brightcove Android SDK V8.2.3.

I tried the media controller UI like this.
![image](https://github.com/BrightcoveOS/android-player-samples/assets/107822703/b0ee78b4-1061-4b78-a821-7228ca7499f0)

And added custom player control icons as below:
![image](https://github.com/BrightcoveOS/android-player-samples/assets/107822703/4a240c40-3445-42e6-9847-e92009226fb8)

And disabled String values for the rewind and forward icons to avoid duplicated and overlapped the default icons.
![image](https://github.com/BrightcoveOS/android-player-samples/assets/107822703/8cda5611-4fe4-4e88-ae36-00907f20b9c2)

But the result is like below. The pause icon is overlapped with the rewind icon.

![image](https://github.com/BrightcoveOS/android-player-samples/assets/107822703/ae788a45-258b-486d-bc4c-0019ade8bc49)

**Comment by nandovelazquez** [comment]
We are closing the Issues feature for this repo next month. If your problem persists, please report it as an issue through our support page: https://sdks.support.brightcove.com/developer-support/questions/report-issue-brightcove-native-sdks.html
