### ISSUE TITLE
Android SDK 8.3.0 and 8.4.0 have build errors

### ISSUE THREAD

**Issue by mharlowfod** [BrightcoveOS/android-player-samples#287]
Hello,

I have recently attempted to upgrade our Android app (production is using 8.2.3) to use the latest brightcove SDK (8.4.0), yet I am seeing build errors occur in android studio when I do this. Is there a migration guide for 8.3.0/8.4.0 or any sample that uses it? It seems like the samples here are using 8.1.x.

Any information would be helpful!

Here is the error (repeated for majority of used Brightcove class references):
error: cannot access BrightcoveCaptionFormat
import com.brightcove.player.captioning.BrightcoveCaptionFormat;
                                       ^
  bad class file: /Users/xxxx/.gradle/caches/transforms-3/6b2406dfe605cc144cacf1288f052b32/transformed/jetified-android-sdk-8.3.0-api.jar(/com/brightcove/player/captioning/BrightcoveCaptionFormat.class)
    class file has wrong version 61.0, should be 55.0
    Please remove or make sure it appears in the correct subdirectory of the classpath.
    
  Thank you,
  
  M. Harlow
  Fitness On Demand Android App

**Comment by nandovelazquez** [comment]
We are closing the Issues feature for this repo next month. If your problem persists, please report it as an issue through our support page: https://sdks.support.brightcove.com/developer-support/questions/report-issue-brightcove-native-sdks.html
