### ISSUE TITLE
Brightcove SDK is using wrong the mutlidex namespace

### ISSUE THREAD

**Issue by wezley98** [BrightcoveOS/android-player-samples#291]
The current version of the brightcove SDK is still using:

`implementation "com.android.support:multidex:2.0.1"`

This results in the following errror when clients try to turn off `android.enableJetifier=false` in `gradle.properties`

```
Caused by: org.gradle.internal.resolve.ModuleVersionNotFoundException: Could not find com.android.support:multidex:2.0.1.
Searched in the following locations:
  - https://dl.google.com/dl/android/maven2/com/android/support/multidex/2.0.1/multidex-2.0.1.pom
  - https://repo.maven.apache.org/maven2/com/android/support/multidex/2.0.1/multidex-2.0.1.pom
```

Please can you migrate to :

`implementation "androidx.multidex:multidex:2.0.1"`

notice the namespace is now `androidx`

See https://developer.android.com/build/multidex

**Comment by nandovelazquez** [comment]
Hi @wezley98. Which version of the SDK are you using?

**Comment by nandovelazquez** [comment]
The SDK migrated to `androidx:multidex` at the beginning of last year(v8.0.0), but the sample apps still used `android.support:multidex`. So, we just migrated the samples to use `androidx:multidex` as well.
