### ISSUE TITLE
Closed caption not visible

### ISSUE THREAD

**Issue by harmanNewscorp** [BrightcoveOS/android-player-samples#295]
Closed captions are not visible for my App.

When I tried to create a new DemoApplication and using this same [Activity](https://github.com/BrightcoveOS/android-player-samples/blob/master/brightcove-exoplayer/BasicSampleApp/src/main/java/com/brightcove/player/samples/exoplayer/basic/MainActivity.java) with same account and video as in this sample App, Video playing fine able to see the cc Icon, and Caption Selection Dialog also, but Caption text not visible on player.

**Comment by nandovelazquez** [comment]
We are closing the Issues feature for this repo. If your problem persists, please report it as an issue through our support page: https://sdks.support.brightcove.com/developer-support/questions/report-issue-brightcove-native-sdks.html
