### ISSUE TITLE
Gradle Plugin 0.11.+ and Gradle 1.12 (required for AS 0.6.1) cause build issues

### ISSUE THREAD

**Issue by bhnath** [BrightcoveOS/android-player-samples#47]
Using the 0.11.+ version of the gradle plugin and the 1.12 version of gradle are causing build time issues fetching the android-native-player libraries from the S3 bucket. For now, Android Studio 0.6.1 is not supported, but will be fixed in the future.

**Comment by BCjwhisenant** [comment]
Closing old issues.
I've built samples and test apps using Android Studio, with various versions of Gradle and the Studio, without issues.
