### ISSUE TITLE
Render problem in Widevive protected videos after seek.

### ISSUE THREAD

**Issue by mketanv1** [BrightcoveOS/android-player-samples#56]
There is a problem in widevine protected videos that; When I seek to position by programatically or manually by seekbar, It looks like looping some sagment of video, and some times, it displays many thumbs types on top.
I am attaching links of probems :
Looping : https://dl.dropboxusercontent.com/u/81270960/big%20bang/VID-20140526-WA0006.mp4

Thumbs : https://dl.dropboxusercontent.com/u/81270960/big%20bang/Photo%202014-07-02%2018.22.31.jpg

Videos, that are not secured by widevine are running fine.

**Comment by BCjwhisenant** [comment]
Closing old issues.
This is not reproducible my be using the current version of the Android SDK (4.8.3).
