### ISSUE TITLE
Display playlists

### ISSUE THREAD

**Issue by jonfreeman33** [BrightcoveOS/android-player-samples#88]
I am wondering if there is a way to display all the videos in a certain playlist on an android device. As it stands right now, I am able to load the first video in the playlist and continue to play through all of the videos. However, I wish the user to be able to select any video in the playlist without having to watch all the videos up to that point.

Any help would be great! Thanks

**Comment by sirvon** [comment]
can you show the code to work with playlist....init player with playlist then play the videos...

thanks!

**Comment by BCjwhisenant** [comment]
Closing this, outdated issue.
